# Generated by the loadout-cli release workflow. Edits here are overwritten on
# the next release: change .github/workflows/homebrew.yml in that repository.
class Loadout < Formula
  desc "Agent launcher that composes project context from a central workspace"
  homepage "https://github.com/ntatschner/loadout-cli"
  version "0.43.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/ntatschner/loadout-cli/releases/download/v0.43.0/loadout-0.43.0-osx-arm64.tar.gz"
      sha256 "c98879286d68254d3b0d77a8edf039a68141ef7fe15fe3da9d77b5d2f2baa2e7"
    end

    on_intel do
      url "https://github.com/ntatschner/loadout-cli/releases/download/v0.43.0/loadout-0.43.0-osx-x64.tar.gz"
      sha256 "8ca7d052bd43043f200c0ebc5362b4a4caa8948d111b978eb0ff3a10a733587b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ntatschner/loadout-cli/releases/download/v0.43.0/loadout-0.43.0-linux-arm64.tar.gz"
      sha256 "c07e65fff3bec259bc6c67a7cb8d232ab58b8b5b77de6938ce1f174f554f9f5f"
    end

    on_intel do
      url "https://github.com/ntatschner/loadout-cli/releases/download/v0.43.0/loadout-0.43.0-linux-x64.tar.gz"
      sha256 "f014cb3a256de0cb4ca3a012f90ffb6d0dd01b3d902b79724b9016a89118b603"
    end
  end

  def install
    # Not `bin.install "loadout"`. The archive carries a native library beside
    # the binary — libonigwrap.dylib on macOS, libonigwrap.so on Linux — and
    # installing the executable on its own leaves it behind, so the whole
    # payload goes to libexec and bin gets a script that execs it there.
    libexec.install Dir["*"]

    bin.write_exec_script libexec/"loadout"
  end

  test do
    # The version is the one thing that can be asserted without a workspace,
    # a registered project or a network: everything else this does needs
    # `loadout setup` to have run.
    assert_match version.to_s, shell_output("#{bin}/loadout --version")
  end
end
