# Generated by the loadout-cli release workflow. Edits here are overwritten on
# the next release: change .github/workflows/homebrew.yml in that repository.
class Loadout < Formula
  desc "Agent launcher that composes project context from a central workspace"
  homepage "https://github.com/ntatschner/loadout-cli"
  version "0.43.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/ntatschner/loadout-cli/releases/download/v0.43.1/loadout-0.43.1-osx-arm64.tar.gz"
      sha256 "50ab8d6e58e4e260305c06ead37cf3d74ec66f5d02feddb614cff29426b4094b"
    end

    on_intel do
      url "https://github.com/ntatschner/loadout-cli/releases/download/v0.43.1/loadout-0.43.1-osx-x64.tar.gz"
      sha256 "4ab372312936f043f1662c90b90e72265675badb312e8563e3213f2a253e09c4"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ntatschner/loadout-cli/releases/download/v0.43.1/loadout-0.43.1-linux-arm64.tar.gz"
      sha256 "98c14f3d7f77de496f05ff889f49de4dd7552074b67f7f54e23992d3e02748c4"
    end

    on_intel do
      url "https://github.com/ntatschner/loadout-cli/releases/download/v0.43.1/loadout-0.43.1-linux-x64.tar.gz"
      sha256 "74435e5c4fb06e06ebd2dcfa0546e2a37cacd99d4e2dcad26801b2732eeb89bf"
    end
  end

  def install
    # Not `bin.install "loadout"`. The archive carries a native library beside
    # the binary — libonigwrap.dylib on macOS, libonigwrap.so on Linux — and
    # installing the executable on its own leaves it behind, so the whole
    # payload goes to libexec and bin gets a script that execs it there.
    libexec.install Dir["*"]

    bin.write_exec_script libexec/"loadout"
  end

  test do
    # The version is the one thing that can be asserted without a workspace,
    # a registered project or a network: everything else this does needs
    # `loadout setup` to have run.
    assert_match version.to_s, shell_output("#{bin}/loadout --version")
  end
end
