# Generated by the loadout-cli release workflow. Edits here are overwritten on
# the next release: change .github/workflows/homebrew.yml in that repository.
class Loadout < Formula
  desc "Agent launcher that composes project context from a central workspace"
  homepage "https://github.com/ntatschner/loadout-cli"
  version "0.33.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/ntatschner/loadout-cli/releases/download/v0.33.1/loadout-0.33.1-osx-arm64.tar.gz"
      sha256 "af327388da9c39b0cdc5b4e387e77af01fb3ce5c20838860f4196e2d758142fa"
    end

    on_intel do
      url "https://github.com/ntatschner/loadout-cli/releases/download/v0.33.1/loadout-0.33.1-osx-x64.tar.gz"
      sha256 "cc2dd5b85977d5657494aaa87a3b89b5344a51deaedd9aa2d8d8fd1dbadf6c2a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ntatschner/loadout-cli/releases/download/v0.33.1/loadout-0.33.1-linux-arm64.tar.gz"
      sha256 "c64c05187b6c0c5b45cf97ccf08a4a38398d8fcd0b8ed6f418b26b2be91ae54f"
    end

    on_intel do
      url "https://github.com/ntatschner/loadout-cli/releases/download/v0.33.1/loadout-0.33.1-linux-x64.tar.gz"
      sha256 "278747091abd910b7c31a90b944593e7d3b3a226b68269bef02b9d0d636fd5c6"
    end
  end

  def install
    # Not `bin.install "loadout"`. The archive carries a native library beside
    # the binary — libonigwrap.dylib on macOS, libonigwrap.so on Linux — and
    # installing the executable on its own leaves it behind, so the whole
    # payload goes to libexec and bin gets a script that execs it there.
    libexec.install Dir["*"]

    bin.write_exec_script libexec/"loadout"
  end

  test do
    # The version is the one thing that can be asserted without a workspace,
    # a registered project or a network: everything else this does needs
    # `loadout setup` to have run.
    assert_match version.to_s, shell_output("#{bin}/loadout --version")
  end
end
